# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Prevent concurrent deployments
concurrency:
  group: "deploy-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.64

    - name: Unit Test
      run: |
        go test ./... -coverpkg ./... -coverprofile cover.out
        go tool cover -func=cover.out | grep total: | grep -Eo '[0-9]+\.[0-9]+'

    - name: Build
      run: go build ./...

    - name: Build Wasm
      run: go build -o web/game.wasm
      env:
        GOOS: js
        GOARCH: wasm

    - name: Copy WASM runtime
      run: cp $(go env GOROOT)/misc/wasm/wasm_exec.js web/

    - name: Archive WASM build
      uses: actions/upload-artifact@v4
      with:
        name: wasm-build
        path: |
          web/
        retention-days: 7

  security:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest && govulncheck ./...

  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: [build, security]

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Download math result for job 1
        uses: actions/download-artifact@v4
        with:
          name: wasm-build
          path: web/

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: web/

      - id: deployment
        uses: actions/deploy-pages@v4